[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd monofloor-admin && npm ci"]

[phases.build]
cmds = ["cd monofloor-admin && npm run build"]

[start]
cmd = "cd monofloor-admin && npm run db:push && npm run start"
