[phases.setup]
nixPkgs = ["nodejs", "python3", "ffmpeg"]

[phases.install]
cmds = [
  "npm ci",
  "pip3 install -r requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run db:push && npm run start"
